apiVersion: v2
name: drupal
version: 0.1.0
appVersion: "10.3.7"
kubeVersion: ">=1.19.0-0"
description: A Helm chart for Kubernetes Drupal 10 deployment
home: https://github.com/TribusStudio/drupal.git
keywords:
  - drupal
  - cms
  - content-management
  - open-source
sources:
  - https://git.drupalcode.org/project/codebase
  - https://github.com/TribusStudio/helm-charts
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: ~16.0.0
    condition: cache.redis.enabled
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: ~11.0.0
    condition: database.mariadb.enabled
  - name: solr
    repository: https://charts.bitnami.com/bitnami
    version: ~6.0.0
    condition: search.solr.enabled
  - name: varnish
    repository: https://charts.bitnami.com/bitnami
    version: ~3.0.0
    condition: varnish.enabled[1]
annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: drupal
      image: bitnami/drupal:10.3.7
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Documentation
      url: https://www.drupal.org/documentation
    - name: tribusstudio/helm-charts
      url: https://github.com/TribusStudio/helm-charts
