apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-drupal-cron
spec:
  schedule: {{ .Values.drupal.cronSchedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: drupal-cron
              image: "{{ .Values.drupal.image.repository }}:{{ .Values.drupal.image.tag }}"
              command:
                - /bin/sh
                - -c
                - drush cron
              env:
                - name: DRUPAL_DATABASE_HOST
                  value: {{ .Release.Name }}-mariadb
          restartPolicy: OnFailure
