apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "drupal.fullname" . }}
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.drupal.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "drupal.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
