apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-drupal-files
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.drupal.persistence.size }}
  storageClassName: {{ .Values.drupal.persistence.storageClass }}
