{{- if and .Values.service (hasKey .Values.service "type") .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "drupal.fullname" . }}
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.drupal.service.type }}
  ports:
    - port: {{ .Values.drupal.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "drupal.labels" . | nindent 4 }}
{{- end }}
