global:
  environment: prod

drupal:
  replicas: 3
  resources:
    limits:
      memory: 2Gi
      cpu: 2000m
  persistence:
    size: 20Gi

database:
  persistence:
    size: 20Gi

cache:
  redis:
    enabled: true
  replicas: 3

varnish:
  enabled: true
  replicas: 2
