global:
  environment: dev

drupal:
  replicas: 1
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
  persistence:
    size: 5Gi

database:
  persistence:
    size: 5Gi

cache:
  redis:
    enabled: false

varnish:
  enabled: false
